# Generated by Django 3.1.4 on 2020-12-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Title Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description of the Title')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=6, verbose_name='Gender')),
                ('slug', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Slug of the Title')),
                ('total_vote', models.PositiveBigIntegerField(default=0, verbose_name='Total No of Vote Registered')),
            ],
            options={
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_vote', models.PositiveBigIntegerField(default=0, verbose_name='Total No of Vote Registered by this student for the event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Student Model')),
                ('title_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.titles', verbose_name='Titles Model')),
            ],
            options={
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
