# Generated by Django 3.1.5 on 2021-01-19 18:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ('colour', '-total_vote', 'title_name'), 'verbose_name_plural': 'Titles'},
        ),
        migrations.AddField(
            model_name='titles',
            name='colour',
            field=colorfield.fields.ColorField(default='#f57e42', max_length=18),
        ),
    ]
