# Generated by Django 3.1.4 on 2021-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20210104_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='gender',
            field=models.CharField(choices=[('ALL', 'ALL'), ('m', 'Male'), ('f', 'Female')], default='m', max_length=6, verbose_name='Gender'),
        ),
    ]
