# Generated by Django 3.1.4 on 2021-01-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20210104_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'ordering': ('-stu_vote', 'title_part'), 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ('-total_vote', 'title_name'), 'verbose_name_plural': 'Titles'},
        ),
    ]
