# Generated by Django 3.1.5 on 2021-01-19 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='vote_nicknameassigntime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 18, 9, 22, 307682), verbose_name='End Time limit of assigning votes and nickname'),
        ),
    ]
