# Generated by Django 3.1.5 on 2021-01-22 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='vote_nicknameassigntime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Time limit of assigning votes and nickname'),
        ),
    ]
