# Generated by Django 3.1.4 on 2021-01-12 16:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram_id',
            field=models.CharField(max_length=254, null=True, validators=[main.models.validate_insta_id]),
        ),
    ]
