# Generated by Django 3.1.4 on 2021-01-05 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210104_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vote_nicknameassigntime_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time limit of assigning votes and nickname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='vote_nicknameassigntime',
            field=models.DateTimeField(verbose_name='End Time limit of assigning votes and nickname'),
        ),
    ]
