# Generated by Django 3.1.5 on 2021-01-13 07:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210112_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('date_time',)},
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=254, null=True, validators=[main.models.validate_insta_id]),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_entry',
            field=models.TextField(blank=True, null=True, verbose_name='The about us on the entry page'),
        ),
    ]
