# Generated by Django 3.1.4 on 2021-01-08 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210105_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date when this confession was added!')),
                ('confession', models.TextField(blank=True, null=True, verbose_name='Confession')),
            ],
        ),
    ]
