# Generated by Django 3.1.5 on 2021-01-14 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('main', '0004_auto_20210113_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date_time',)},
        ),
        migrations.CreateModel(
            name='RemoveName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
            options={
                'verbose_name_plural': 'Remove Name',
            },
        ),
    ]
