# Generated by Django 3.1.5 on 2021-01-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210114_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removename',
            old_name='name',
            new_name='student_models',
        ),
    ]
