# Generated by Django 3.1.5 on 2021-01-14 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210114_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='removename',
            name='time_field',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
