# Generated by Django 3.1.4 on 2021-01-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_titles_title_stu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='title_stu',
            field=models.CharField(choices=[('ALL', 'ALL'), ('SC-1', 'SC-1'), ('SC-2', 'SC-2'), ('SC-3', 'SC-3'), ('COMMERCE', 'COMMERCE'), ('ARTS', 'ARTS')], default='sc1', max_length=10, verbose_name='Class'),
        ),
    ]
