# Generated by Django 3.1.4 on 2020-12-29 14:47

import django.contrib.postgres.fields.hstore
import django.core.files.storage
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name of the Student')),
                ('slug', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Slug of the Student')),
                ('profile_pic', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=student.models.path_and_rename)),
                ('class_stu', models.CharField(choices=[('sc1', 'SC-1'), ('sc2', 'SC-2'), ('sc3', 'SC-3'), ('com', 'COMMERCE'), ('arts', 'ARTS')], default='sc1', max_length=6, verbose_name='Class')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=6, verbose_name='Gender')),
                ('note', models.TextField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True, verbose_name='Title given by the others')),
            ],
        ),
    ]
