# Generated by Django 3.1.4 on 2020-12-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Title given by the others'),
        ),
    ]
