# Generated by Django 3.1.4 on 2020-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201229_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Title given by the others'),
        ),
    ]
