# Generated by Django 3.1.4 on 2021-01-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210104_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('class_stu', 'name')},
        ),
    ]
