# Generated by Django 3.1.4 on 2020-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201229_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.TextField(default=dict, verbose_name='Title given by the others'),
        ),
    ]
